GET http://localhost:3000/api/blogs


### Get all users
GET http://localhost:3000/api/users
Authorization: Basic YWRtaW46cXdlcnR5 

###Login Router
POST http://localhost:3000/api/auth/login
content-type: application/json

 {
   "loginOrEmail": "Nadeen",
   "password": "myDaughter"
 }


###auth/me
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTI2Njc2NjAyNzMxNmFjZjFlNDQyMTciLCJpYXQiOjE2OTgwNTQyMDAsImV4cCI6MTY5ODA1NDIzMH0.eSRHLaYc8N5jy14rcJkaXbGO-E7Eqmv96aJBtpXj3Q4

### Refresh Token route
POST http://localhost:3000/api/auth/refresh-token



